# Uncomment the next line to define a global platform for your project
source 'https://github.com/priankakariatyml/tfltask-pod-test.git'
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '12.0'

target 'ImageClassification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageClassification
   pod 'TensorFlowLiteSwift'
   pod 'TensorFlowLiteTaskVision'
end
