source 'https://github.com/priankakariatyml/tfltask-pod-test.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'ImageClassification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageClassification

  pod 'TensorFlowLiteTaskVision', '~>0.1.0'

end
