# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/priankakariatyml/mpp-task-pod-test.git'

target 'ImageClassification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageClassification
   #pod 'TensorFlowLiteSwift'
   pod 'MediaPipeTasksVision', '~>5.6.5'
   pod 'MediaPipeTasksText', '~>5.6.5'

end
